name: run-tests-on-pr-or-push
on:
  workflow_dispatch: # allows manual triggering
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v1
      - run: nix build .#nixosConfigurations.smarthub-ng.config.system.build.toplevel
